author: Gerhard Lanz
markdown: CommonMark
title: Gerhard Lanz
url: https://gerhardla.nz
permalink: /:title
repository: gerhardlanz/gerhardla.nz

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false