author: Gerhard Lanz
markdown: CommonMark
permalink: /:title
repository: gerhardlanz/gerhardla.nz
title: Gerhard Lanz
url: https://gerhardla.nz

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap

markdown: CommonMark
commonmark:
  options: ["SMART", "FOOTNOTES", "UNSAFE", "HARDBREAKS"]
  extensions: ["strikethrough", "autolink", "table"]

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
