author: Gerhard Lanz
markdown: CommonMark
permalink: /:title
repository: gerhardlanz/gerhardla.nz
title: Gerhard Lanz

url: https://gerhardla.nz

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap
  - jekyll-titles-from-headings

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
