markdown: CommonMark
permalink: /:title
title: Gerhard Lanz

collections:
  notes:
    output: true
    permalink: /:title
    
plugins:
  - jekyll-feed
  - jekyll-sitemap

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
