author: Gerhard Lanz
description: (he/him)
markdown: kramdown
title: Gerhard Lanz
url: https://gerhardla.nz
permalink: /:title/

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-readme-index
  - jekyll-sitemap

readme_index:
  enabled: true
  remove_originals: false
  with_frontmatter: false
