title: Gerhard
markdown: CommonMark
repository: gerhardlanz/gerhardla.nz
url: https://gerhardla.nz
permalink: /:title
future: true

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-titles-from-headings

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
