title: Gerhard Lanz
markdown: CommonMark
repository: gerhardlanz/gerhardla.nz
url: https://gerhardla.nz
permalink: /:title

plugins:
  - jekyll-commonmark
  - jekyll-feed
  - jekyll-readme-index
  - jekyll-sitemap
  - jekyll-titles-from-headings

markdown: CommonMark
commonmark:
  options: ["smart", "unsafe", "hardbreaks"]
